spring:
  #配置项目名称
  application:
    name: springboot-mp
  #配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.132.190.142:3306/exam?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
  thymeleaf:
    cache: false # 开发时关闭缓存,不然没法看到实时页面
    mode: HTML # 用非严格的 HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
#配置端口
server:
  port: 8080
#配置mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jiangzhu.entity

#日志配置(配置mybatis的sql打印)
logging:
  level:
    com.changan.springboot_mybatis.mapper.*: debug

